version: '3.5'
services:
  database:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - '5432:5432'

  extract_load:
    image: extract_load
    build:
      context: . 
      dockerfile: ./dockerfiles/el.dockerfile
    env_file: .env
    command: ["python3","extract_load.py"]
    depends_on:
      - database
  kwv:
    image: kwv
    build:
      context: .
      dockerfile: ./dockerfiles/kwv.dockerfile
    env_file: .env
    command: [  "sleep","20","&&",
                "dbt","seed","--full-refresh","--profiles-dir","./","&&",
                "dbt","run","--profiles-dir","./"]
    depends_on:
      - database

#  dash:
#    image: dash
#    build:
#      context: .
#      dockerfile: ./dockerfiles/dash.dockerfile
#    env_file: .env
#    ports:
#      - "8050:8050"

