version: '3.5'
services:
  database:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - '5432:5432'

  extract_load:
    image: extract_load
    build:
      context: . 
      dockerfile: ./dockerfiles/el.dockerfile
    env_file: .env
    command: sh -c "sleep 10 && python3 extract_load.py"
    depends_on:
      - database
  kwv:
    image: kwv
    build:
      context: .
      dockerfile: ./dockerfiles/kwv.dockerfile
    env_file: .env
    volumes:
      - ./transforms:/app
    command: sh -c "sleep 10 && tail -f /dev/null"    
    depends_on:
      - database

#  dash:
#    image: dash
#    build:
#      context: .
#      dockerfile: ./dockerfiles/dash.dockerfile
#    env_file: .env
#    ports:
#      - "8050:8050"

